version: '3.6'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    expose:
    - 9090
    ports:
      - 9090:80
    volumes:
    - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - dp-server

  dp-server:
    image: datapane/dp-server:latest
    restart: unless-stopped
    expose:
    - 8090
    env_file: ./datapane.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    command: ["poetry", "run", "./local.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/site/watchman/ping/?watchman-token=glitchcore"]
      interval: 60s
      timeout: 20s
      retries: 2

  celery-default-io:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    command: ["poetry", "run", "celery", "--app=celery_main:app worker", "--queues=io_bound,celery", "--pool=threads", "--concurrency=5"]

  celery-cpu:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    command: ["poetry", "run", "celery", "--app=celery_main:app worker", "--queues=cpu_bound", "--pool=prefork"]

  celery-beat:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    command: ["poetry", "run", "celery", "--app=celery_main:app", "beat"]

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - 'redis_1_data:/data:Z'
    command: ["redis-server","--maxmemory", "32mb", "--maxmemory-policy", "allkeys-lru"]

volumes:
  redis_1_data: