version: '3.6'
services:
  server:
    image: datapane/dp-server:latest
    restart: unless-stopped
    ports:
    - "8090:8090"
    env_file: ./datapane.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    command: ["./local.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/site/watchman/ping/"]
      interval: 60s
      timeout: 20s
      retries: 2

  celery-default-io:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    command: ["celery", "--app=celery_main:app worker", "--queues=io_bound,celery", "--pool=threads", "--concurrency=5"]

  celery-cpu:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    command: ["celery", "--app=celery_main:app worker", "--queues=cpu_bound", "--pool=prefork"]

  celery-beat:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    command: ["celery", "--app=celery_main:app", "beat"]

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    expose:
      - 6379
    # uncomment to expose redis to host
    # ports:
    #   - "6379:6379"
    volumes:
      - "redis_5_data:/data:Z"
    command: ["redis-server", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru", "--appendonly", "yes"]

volumes:
  redis_5_data:
