version: '3.6'
services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - 'pg_12_data:/var/lib/postgresql/data:Z'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datapane

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - 'redis_5_data:/data:Z'
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "32mb", "--maxmemory-policy", "allkeys-lru", "--appendonly", "yes"]

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - 'minio_1_data:/export:Z'
      - 'minio_1_config:/root/.minio:Z'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    # command: ["server", "start"]
    entrypoint: sh
    command: -c 'mkdir -p /export/datapane && /usr/bin/minio server /export'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pg_12_data:
  minio_1_data:
  minio_1_config:
  redis_5_data:
