version: '3.6'
services:
  server:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    expose:
    - 8090
    ports:
    - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["./local.sh"]
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:80/site/watchman/ping/"]
      interval: 60s
      timeout: 20s
      retries: 2

  celery-default-io:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    environment:
      C_FORCE_ROOT: 1
    command: ["celery", "--app=celery_main:app", "worker", "--queues=io_bound,celery", "--pool=threads", "--concurrency=5"]
    depends_on:
      - redis

  celery-cpu:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    environment:
      C_FORCE_ROOT: 1
    command: ["celery", "--app=celery_main:app", "worker", "--queues=cpu_bound", "--pool=prefork"]
    depends_on:
      - redis

  celery-beat:
    image: datapane/dp-server:latest
    restart: unless-stopped
    env_file: ./datapane.env
    command: ["celery", "--app=celery_main:app", "beat"]
    depends_on:
      - redis

  redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    expose:
      - 6379
    # uncomment to expose redis to host
    #ports:
    #  - "6379:6379"
    volumes:
      - "redis_6_data:/data:Z"
    command: ["redis-server", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru",
              "--appendonly", "yes", "--timeout", "43200"]

volumes:
  redis_6_data:
